# Generated by Django 5.1.7 on 2025-03-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_economiccalendar_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='economiccalendar',
            name='event_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
