# Generated by Django 5.1.7 on 2025-03-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_rename_content_news_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='published_at',
            new_name='published_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='entity_name',
        ),
        migrations.RemoveField(
            model_name='news',
            name='entity_symbol',
        ),
        migrations.RemoveField(
            model_name='news',
            name='sentiment_score',
        ),
        migrations.AddField(
            model_name='news',
            name='ticker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
