# Generated by Django 5.1.7 on 2025-03-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_rename_published_at_news_published_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='published_date',
            new_name='published_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='source',
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
