# Generated by Django 5.1.7 on 2025-03-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_rename_published_date_news_published_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50, unique=True)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=50)),
            ],
        ),
    ]
