# Generated by Django 5.1.7 on 2025-03-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='author',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='source',
        ),
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='replies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweets',
            field=models.IntegerField(default=0),
        ),
    ]
