# Generated by Django 5.1.7 on 2025-04-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_rename_text_tweet_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='economiccalendar',
            old_name='category',
            new_name='impact',
        ),
        migrations.RenameField(
            model_name='economiccalendar',
            old_name='country',
            new_name='time',
        ),
        migrations.AddField(
            model_name='economiccalendar',
            name='graph',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
