# Generated by Django 5.1.7 on 2025-04-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_rename_category_economiccalendar_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='economiccalendar',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='economiccalendar',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
