# Generated by Django 5.1.7 on 2025-04-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_economiccalendar_category_economiccalendar_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='name',
        ),
    ]
