# Generated by Django 5.1.7 on 2025-04-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_remove_symbol_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxOptionExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('image', models.ImageField(upload_to='forexlive_images')),
            ],
        ),
        migrations.CreateModel(
            name='COTReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('open_interest', models.BigIntegerField()),
                ('commercial_long', models.BigIntegerField()),
                ('commercial_short', models.BigIntegerField()),
                ('non_commercial_long', models.BigIntegerField()),
                ('non_commercial_short', models.BigIntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.symbol')),
            ],
            options={
                'unique_together': {('symbol', 'report_date')},
            },
        ),
    ]
